#! /usr/bin/env bash

out=$1
#### Extract the fastq(s) ####
# load the libraries needed
module load StdEnv/2020
module load gcc/9.3.0
module load sra-toolkit

## put in a check for "if the folder already exists, skip this step"
if [[ ! -d "~/scratch/Afumigatus_WGSA_Raw_Fastqs/${out}" ]]; then
        fasterq-dump ${sample} -O ~/scratch/Afumigatus_WGSA_Raw_Fastqs/${out} 
        cd ~/scratch/Afumigatus_WGSA_Raw_Fastqs/${out}
        gzip *
        echo "exists now"
else 
    echo "${out} exists already"
fi

echo "done"